<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-critters-container>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{{ asset('assets/h2color.svg') }}" type="image/svg+xml">
        <title>Househunter</title>
    <style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css" media="all"></noscript><style>:root{--acc-hue: 166;--solids-sat: 3%;--acc: var(--acc-hue), 87%, 49%;--gray: var(--acc-hue), var(--solids-sat), 50%;--fg: var(--acc-hue), var(--solids-sat), 95%;--bg: var(--acc-hue), var(--solids-sat), 12%;--gap-size: 1em}body{background-color:hsl(var(--bg));color:hsl(var(--fg));margin:0;min-height:100vh}*{font-family:Overpass Mono,monospace}*{transition-duration:.3s}
</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css"></noscript></head>
    <body>
        <app-root></app-root>
        <script src="{{ asset('polyfills.js') }}" type="module"></script>
        <script src="{{ asset('main.js') }}" type="module"></script>
    <script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script></body>
</html>
